(custom-set-variables
 '(frame-background-mode "black")
 '(show-trailing-whitespace t))

(custom-set-faces
 '(default ((t (:foreground "white" :background "black"))))
 '(diff-added ((t (:background "#003000"))))
 '(diff-hunk-header ((t (:background "blue"))))
 '(diff-removed ((t (:background "#300000"))))
 '(font-lock-builtin-face ((((class color) (background dark))
                            (:foreground "Turquoise"))))
 '(font-lock-comment-face ((t (:foreground "MediumAquamarine"))))
 '(font-lock-constant-face ((((class color) (background dark))
                             (:bold t :foreground "DarkOrchid"))))
 '(font-lock-doc-string-face ((t (:foreground "green2"))))
 '(font-lock-function-name-face ((t (:foreground "SkyBlue"))))
 '(font-lock-keyword-face ((t (:bold t :foreground "CornflowerBlue"))))
 '(font-lock-preprocessor-face ((t (:italic nil :foreground "CornFlowerBlue"))))
 '(font-lock-reference-face ((t (:foreground "DodgerBlue"))))
 '(font-lock-string-face ((t (:foreground "LimeGreen"))))
 '(font-lock-type-face ((t (:foreground "#9290ff"))))
 '(font-lock-variable-name-face ((t (:foreground "PaleGreen"))))
 '(font-lock-warning-face ((((class color) (background dark))
                            (:foreground "black" :bold t :background "gold"))))
 '(highlight ((t (:background "CornflowerBlue"))))
 '(isearch ((t (:background "cornflowerblue"))))
 '(list-mode-item-selected ((t (:background "gold"))))
 '(makefile-space-face ((t (:background "wheat"))))
 '(mode-line ((t (:background "Navy"))))
 '(paren-match ((t (:background "darkseagreen4"))))
 '(region ((t (:background "DarkSlateBlue"))))
 '(show-paren-match ((t (:background "#444464"))))
 '(show-paren-mismatch ((t (:background "#600000"))))
 '(trailing-whitespace ((((class color) (background dark))
                         (:background "gold"))))
 )

;; Colorify figures
(make-face 'my-zero-face)
(set-face-foreground 'my-zero-face "white")
(make-face 'my-one-face)
(set-face-foreground 'my-one-face "blue")
(make-face 'my-two-face)
(set-face-foreground 'my-two-face "red")
(make-face 'my-three-face)
(set-face-foreground 'my-three-face "orange")
(make-face 'my-four-face)
(set-face-foreground 'my-four-face "yellow")
(make-face 'my-five-face)
(set-face-foreground 'my-five-face "cyan")
(make-face 'my-six-face)
(set-face-foreground 'my-six-face "green")
(make-face 'my-seven-face)
(set-face-foreground 'my-seven-face "violet")
(make-face 'my-eigth-face)
(set-face-foreground 'my-eigth-face "magenta")
(make-face 'my-nine-face)
(set-face-foreground 'my-nine-face "grey")
(font-lock-add-keywords 'c++-mode
                        '(("\\<\\(FIXME\\):" 1 font-lock-warning-face prepend)
                          ("\\<0\\>" . 'my-zero-face)
                          ("\\<1\\>" . 'my-one-face)
                          ("\\<2\\>" . 'my-two-face)
                          ("\\<3\\>" . 'my-three-face)
                          ("\\<4\\>" . 'my-four-face)
                          ("\\<5\\>" . 'my-five-face)
                          ("\\<6\\>" . 'my-six-face)
                          ("\\<7\\>" . 'my-seven-face)
                          ("\\<8\\>" . 'my-eight-face)
                          ("\\<9\\>" . 'my-nine-face)
                          ))


(provide 'text-display)
