;; Colorify figures
(make-face 'my-zero-face)
(set-face-foreground 'my-zero-face "white")
(make-face 'my-one-face)
(set-face-foreground 'my-one-face "blue")
(make-face 'my-two-face)
(set-face-foreground 'my-two-face "red")
(make-face 'my-three-face)
(set-face-foreground 'my-three-face "orange")
(make-face 'my-four-face)
(set-face-foreground 'my-four-face "yellow")
(make-face 'my-five-face)
(set-face-foreground 'my-five-face "cyan")
(make-face 'my-six-face)
(set-face-foreground 'my-six-face "green")
(make-face 'my-seven-face)
(set-face-foreground 'my-seven-face "violet")
(make-face 'my-eigth-face)
(set-face-foreground 'my-eigth-face "magenta")
(make-face 'my-nine-face)
(set-face-foreground 'my-nine-face "grey")
(font-lock-add-keywords 'c++-mode
                        '(("\\<\\(FIXME\\):" 1 font-lock-warning-face prepend)
                          ("\\<0\\>" . 'my-zero-face)
                          ("\\<1\\>" . 'my-one-face)
                          ("\\<2\\>" . 'my-two-face)
                          ("\\<3\\>" . 'my-three-face)
                          ("\\<4\\>" . 'my-four-face)
                          ("\\<5\\>" . 'my-five-face)
                          ("\\<6\\>" . 'my-six-face)
                          ("\\<7\\>" . 'my-seven-face)
                          ("\\<8\\>" . 'my-eight-face)
                          ("\\<9\\>" . 'my-nine-face)
                          ))


(provide 'text-display)
